### ISSUE TITLE
Init command behaves too silently

### ISSUE THREAD

**Issue by PropheticBird** [ikalnitsky/holocron#103]
When user executes `holocron init` nothing special is happening: a small delay and shell is ready to accept new command. It would be good if we add some kind of message, which tells what has actually happened and what options user have. 

Something like this:

```bash 
> $ holocron init

Simple blog template has been just created by Holocron. 
Now you can build a blog using `holocron build`.
Then you can see result typing `holocron serve`.  
```

**Comment by ikalnitsky** [comment]
Yep, your proposal is pretty good, though I'm not sure about message.

**Comment by ikalnitsky** [comment]
What  about something like

```
$ holocron init

Done.

Run "holocron build" for compiling sources into HTML.
Run "holocron serve" for previewing your blog in browser.
```

Messages are discussable.

**Comment by ikalnitsky** [comment]
I'm working on it right now as part of another patch. So, what do you think about next message?

```
$ holocron init
The current working directory has been initialized with an example content.

Run "holocron build" if you want to compile content into HTML.
Run "holocron serve" if you want to preview content in browser.

Enjoy! :)
```
?

**Comment by PropheticBird** [comment]
I think messages are good. One thing, I'm not quite sure about, is `an example content`.. I don't like the sound of this.. But I cannot come up with something better than `a blog template`. 
So, if you don't have any other suggestions, lets use what you've proposed.

**Comment by ikalnitsky** [comment]
I think "template" is a right word here, though I don't like how it will look in the following messages:

```
Run "holocron build" if you want to compile template into HTML.
Run "holocron serve" if you want to preview template in browser.
```

It looks weird. I'd like to emphasise that these commands are not about template, they are about users' content. Do you have any suggestion?

**Comment by ikalnitsky** [comment]
Ok, what about this?

```
The current working directory has been initialized with a blog
template. Here's some commands you might be interested in:

   $ holocron build     # compile blog into static html
   $ holocron serve     # preview blog in your browser

Look at the documentation https://holocron.readthedocs.org for
details.

May the Force be with you!
```
