### ISSUE TITLE
Tags parsing problem

### ISSUE THREAD

**Issue by PropheticBird** [ikalnitsky/holocron#29]
Currently, each blogpost must have some tags [0-N]. If a user wants to add tag, he does it using the following syntax:
```markdown
author: Obi-Wan Kenobi
tags: [jedi]
```
Note, that even if there is only one tag, it must be wrapped with `[ ]`. Otherwise, if we specify tags without the square brackets (which is more natural in case of a single tag), like this: 
```markdown
author: Obi-Wan Kenobi
tags: jedi
```
Holocron will interpret each letter of the tag name as a separate tag, so this will lead to creation of tags: `j`, `e`, `d`, `i`. This is not a behavior we would like to expect. Moreover, there is even no warnings, which can explicitly tell, that there were an error in tag parsing.

**Comment by ikalnitsky** [comment]
Well, I thought about this issue and now I believe that the best what we can do is to implement check in `Tags` generator. So I propose do not build tags if post's `tags` attribute isn't list/tuple and print a warning that it supposed to be either list or tuple.

@PropheticBird what do you think? Could you please implement a patch?

**Comment by PropheticBird** [comment]
I don't see any other way of doing this either. OK, that will be my next task.
